# -*- coding: utf-8 -*-
"""histopathological classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11kvAlpFY00MdyRUWJ1b2m9vnMu0tEX_6
"""

! mkdir cancernet

from google.colab import drive
drive.mount('/content/drive')

! python build_dataset.py

! python train_model.py

! cp -r idc /content/drive/My\ Drive/ssingh

! cp model.h5  /content/drive/My\ Drive/ssingh

! cp model.json    /content/drive/My\ Drive/ssingh

! cp plot.png   /content/drive/My\ Drive/ssingh

! cp -r cancernet/    /content/drive/My\ Drive/ssingh

! cp build_dataset.py train_model.py    /content/drive/My\ Drive/ssingh